In [ ]:
import pandas as pd

# List of all the file names shown in your directory
dbaasp_peptide_csv = [
    "peptides 0-2000.csv",
    "peptides 2000-4000.csv",
    "peptides 4000-6000.csv",
    "peptides 6000-8000.csv",
    "peptides 8000-10000.csv",
    "peptides 10000-12000.csv",
    "peptides 12000-14000.csv",
    "peptides 14000-16000.csv",
    "peptides 16000-18000.csv",
    "peptides 18000-20000.csv",
    "peptides 20000-22000.csv",
    "peptides 22000-24000.csv",
    "peptides 24000-25542.csv"
]

In [ ]:
df = pd.concat([pd.read_csv(file) for file in dbaasp_peptide_csv], ignore_index=True)

In [ ]:
print(f"no.of rows = {df.shape[0]}")
print(f"no.of columns = {df.shape[1]}")

no.of rows = 25542
no.of columns = 9

In [ ]:
df.head()

,ID,COMPLEXITY,NAME,N TERMINUS,SEQUENCE,C TERMINUS,SYNTHESIS TYPE,TARGET GROUP,TARGET OBJECT
0,1,Multimer,Distinctin,NaN,NLVSGLIEARKYLEQLHRKLKNCKV ENREVPPGFTALIKTLR...,NaN,Ribosomal,Gram+ Gram-,Lipid Bilayer
1,3,Multimer,Halocidin,NaN,WLNALLHHGLNCAKGVLA ALLHHGLNCAKGVLA,AMD AMD,Ribosomal,Gram+,Lipid Bilayer
2,4,Multimer,Khal,NaN,KWLNALLHHGLNCAKGVLA ALLHHGLNCAKGVLA,AMD AMD,Synthetic,Gram+ Gram-,Lipid Bilayer
3,6,Multi-Peptide,Enterocin X,NaN,SNDSLWYGVGQFMGKQANCITNHPVKHMIIPGYCLSKILG IA...,NaN,Ribosomal,Gram+,Lipid Bilayer
4,7,Multi-Peptide,EAFP1 + EAFP2,NaN,XTCASRCPRPCNAGLCCSIYGYCGSGNAYCGAGNCRCQCRG X...,NaN,Ribosomal,Fungus,Lipid Bilayer

In [ ]:
df.columns

Index(['ID', 'COMPLEXITY', 'NAME', 'N TERMINUS', 'SEQUENCE', 'C TERMINUS',
       'SYNTHESIS TYPE', 'TARGET GROUP', 'TARGET OBJECT'],
      dtype='object')

In [ ]:
df['COMPLEXITY'].value_counts()

COMPLEXITY
Monomer          24867
Multimer           439
Multi-Peptide      236
Name: count, dtype: int64

###this tells we can make classes for complexity
we can checkec similarly for other columns

In [ ]:
df['SYNTHESIS TYPE'].value_counts()

SYNTHESIS TYPE
Synthetic       21049
Ribosomal        3409
Nonribosomal     1084
Name: count, dtype: int64

In [ ]:
df['TARGET GROUP'].value_counts()

TARGET GROUP
Gram+    Gram-    Mammalian Cell                                     5847
Gram+    Gram-                                                       3876
Gram+    Gram-    Fungus    Mammalian Cell                           2590
Gram+    Gram-    Fungus                                             1756
Gram+    Gram-    Cancer    Mammalian Cell                           1363
                                                                     ...
Insect    Cancer    Fungus    Mammalian Cell    Biofilm                 1
Gram+    Gram-    Archaea                                               1
Gram+    Gram-    Virus    Fungus    Mammalian Cell    Biofilm          1
Gram+    Gram-    Cancer    Mammalian Cell    Nematode    Biofilm       1
Gram+    Virus    Fungus    Mammalian Cell                              1
Name: count, Length: 187, dtype: int64

in data for target group it is not proper format. We can format multiple target groups for a sequence in a list to access them easily later as required

In [ ]:
target_groups = [
    "Gram+",
    "Gram-",
    "Mammalian Cell",
    "Fungus",
    "Cancer",
    "Virus",
    "Biofilm",
]

In [ ]:
import pandas as pd

df['tokenised_TARGET GROUP'] = (
    df['TARGET GROUP']
    .fillna('')
    .str.replace('Mammalian Cell', 'Mammalian_Cell', regex=False)
    .str.split()
)

df['tokenised_TARGET GROUP'] = df['tokenised_TARGET GROUP'].apply(
    lambda items: [item.replace('_', ' ') for item in items]
)

In [ ]:
df[['TARGET GROUP', 'tokenised_TARGET GROUP']].head()

     TARGET GROUP tokenised_TARGET GROUP
0  Gram+    Gram-         [Gram+, Gram-]
1           Gram+                [Gram+]
2  Gram+    Gram-         [Gram+, Gram-]
3           Gram+                [Gram+]
4          Fungus               [Fungus]

In [ ]:
df['tokenised_TARGET GROUP'] = df['tokenised_TARGET GROUP'].astype(str)

In [ ]:
df[['TARGET GROUP', 'tokenised_TARGET GROUP']].head()

     TARGET GROUP tokenised_TARGET GROUP
0  Gram+    Gram-     ['Gram+', 'Gram-']
1           Gram+              ['Gram+']
2  Gram+    Gram-     ['Gram+', 'Gram-']
3           Gram+              ['Gram+']
4          Fungus             ['Fungus']

now we have fixed the target group column

will check more features in the dataset

In [ ]:
df['TARGET OBJECT'].head(15)

0                          Lipid Bilayer
1                          Lipid Bilayer
2                          Lipid Bilayer
3                          Lipid Bilayer
4                          Lipid Bilayer
5                          Lipid Bilayer
6                          Lipid Bilayer
7                          Lipid Bilayer
8                          Lipid Bilayer
9                          Lipid Bilayer
10                         Lipid Bilayer
11    Lipid Bilayer    Virus replication
12     Lipid Bilayer    Immunomodulation
13                         Lipid Bilayer
14                         Lipid Bilayer
Name: TARGET OBJECT, dtype: object

In [ ]:
df['TARGET OBJECT'].value_counts().to_dict()

{'Lipid Bilayer': 19416,
 'Virus entry': 639,
 'Cytoplasmic Protein    Lipid Bilayer': 329,
 'Lipid Bilayer    DNA / RNA': 286,
 'Membrane Protein': 205,
 'Lipid II': 186,
 'Cytoplasmic Protein': 180,
 'Unknown': 170,
 'Virus Integrase': 162,
 'Lipid Bilayer    Ribosome': 159,
 'Quorum Sensing': 157,
 'Membrane Protein    Lipid Bilayer': 117,
 'Cytoplasmic Protein    Lipid Bilayer    Ribosome': 109,
 'Lipid Bilayer    Virus replication': 98,
 'Lipid Bilayer    Lipid II': 89,
 'Virus replication': 80,
 'gp41    Virus entry': 79,
 'Membrane Protein    Quorum Sensing': 79,
 'Mitochondrial membrane': 75,
 'Virus Protease': 62,
 'Lipid Bilayer    Virus entry': 55,
 'Lipid Bilayer    Immunomodulation': 48,
 'Virus replication    Virus entry': 46,
 'DNA / RNA': 38,
 'Lysosomal membrane': 36,
 'gp41    Virus replication': 28,
 'Virus Reverse Transcriptase': 26,
 'Virus Protease    Virus replication': 23,
 'Membrane Protein    DNA / RNA': 20,
 'Ribosome': 20,
 'Lipid Bilayer    Mitochondrial membrane': 19,
 'Cytoplasmic Protein    Ribosome': 19,
 'Quorum Sensing    Immunomodulation': 18,
 'Virus entry    Sgp': 16,
 'Virus entry    gB': 10,
 'Lipid Bilayer    Virus Reverse Transcriptase': 9,
 'Lipid Bilayer    DNA / RNA    Immunomodulation': 8,
 'Membrane Protein    Cytoplasmic Protein    Lipid Bilayer': 8,
 'Cytoplasmic Protein    Lipid Bilayer    DNA / RNA': 8,
 'Immunomodulation': 7,
 'gpHA': 7,
 'Membrane Protein    Lipid Bilayer    Virus entry    gp120': 6,
 'Virus entry    gpE': 6,
 'Virus entry    gE': 6,
 'Virus replication    Virus entry    gpHA': 6,
 'Virus entry    EgpDV': 6,
 'Lipid Bilayer    Virus Protease': 5,
 'Virus Integrase    Virus Reverse Transcriptase': 5,
 'Lysosomal membrane    Mitochondrial membrane': 5,
 'Virus entry    gp120': 4,
 'Lipid Bilayer    Sgp': 4,
 'Virus Reverse Transcriptase    Virus entry': 4,
 'Lipid Bilayer    Virus replication    Virus entry': 4,
 'APJ receptor    Virus entry': 4,
 'Membrane Protein    Cytoplasmic Protein': 3,
 'VIF': 3,
 'Lipid Bilayer    Immunomodulation    Ribosome': 3,
 'Virus Integrase    Virus replication': 3,
 'Lipid Bilayer    Virus entry    gD': 3,
 'Virus replication    Virus entry    EgpDV': 3,
 'DNA / RNA    Quorum Sensing': 2,
 'Virus replication    Immunomodulation': 2,
 'Cytoplasmic Protein    Immunomodulation    Ribosome': 2,
 'Cytoplasmic Protein    Immunomodulation': 2,
 'Cytoplasmic Protein    Lipid Bilayer    Virus replication': 2,
 'Lipid Bilayer    Virus replication    Ribosome': 2,
 'Lipid Bilayer    Virus replication    Virus entry    Sgp    Immunomodulation': 2,
 'Membrane Protein    Lipid Bilayer    DNA / RNA': 2,
 'Lipid Bilayer    Virus replication    Immunomodulation': 2,
 'Cytoplasmic Protein    Virus replication    Virus entry    gp120': 2,
 'Cytoplasmic Protein    Quorum Sensing': 2,
 'Virus replication    Virus entry    Sgp': 2,
 'Cytoplasmic Protein    Mitochondrial membrane': 2,
 'DNA / RNA    Ribosome': 2,
 'Lipid Bilayer    Virus replication    Sgp': 2,
 'Quorum Sensing    Mitochondrial membrane    Immunomodulation': 2,
 'Membrane Protein    Quorum Sensing    Immunomodulation': 2,
 'Lipid Bilayer    DNA / RNA    Virus replication': 1,
 'Lipid Bilayer    DNA / RNA    Virus Integrase    Virus replication': 1,
 'Lipid Bilayer    Virus Protease    Virus replication    Virus entry': 1,
 'Lipid Bilayer    Virus replication    gp120    Immunomodulation': 1,
 'Membrane Protein    Lipid Bilayer    Virus replication': 1,
 'Lipid Bilayer    Virus Reverse Transcriptase    Ribosome': 1,
 'Lipid Bilayer    DNA / RNA    Virus entry    gD': 1,
 'Cytoplasmic Protein    Lipid Bilayer    Virus replication    gp120    Immunomodulation': 1,
 'gp41    Virus replication    Virus entry': 1,
 'Lipid Bilayer    Virus entry    Sgp': 1,
 'Lipid Bilayer    gp41    Virus replication    Virus entry': 1,
 'Cytoplasmic Protein    Virus replication    Virus entry    Mitochondrial membrane': 1,
 'Lipid Bilayer    gp41    Virus entry': 1,
 'Lipid Bilayer    DNA / RNA    Lipid II': 1,
 'Cytoplasmic Protein    Lipid Bilayer    Immunomodulation': 1,
 'Cytoplasmic Protein    Virus entry    gpE': 1,
 'Lipid Bilayer    Virus replication    Virus entry    gpHA': 1,
 'Virus replication    Virus entry    gp120    Sgp': 1,
 'Membrane Protein    Lipid Bilayer    Virus replication    Mitochondrial membrane': 1,
 'Membrane Protein    Lipid II': 1,
 'Cytoplasmic Protein    Virus replication    Immunomodulation    Ribosome': 1,
 'Membrane Protein    Lipid Bilayer    Mitochondrial membrane': 1,
 'Lipid Bilayer    Virus replication    Virus entry    gp120': 1,
 'Cytoplasmic Protein    Virus replication    Immunomodulation': 1,
 'Cytoplasmic Protein    Mitochondrial membrane    Immunomodulation': 1,
 'Cytoplasmic Protein    Lipid Bilayer    Mitochondrial membrane': 1,
 'Lipid Bilayer    DNA / RNA    Mitochondrial membrane': 1}

I wrote down all the unique TARGET OBJECTS TOKENS within a a entry
so that we can easily tokenize each entry and filter based on our requirement later

In [ ]:
import re
import pandas as pd

# 1. Define all possible valid target objects in your dataset
known_objects = [
    'Lipid Bilayer',
    'Virus entry',
    'Cytoplasmic Protein',
    'Virus Integrase',
    'DNA / RNA',
    'Virus replication',
    'Virus Protease',
    'Virus Reverse Transcriptase',
    'gp41',
    'Membrane Protein',
    'Immunomodulation',
    'EgpDV',
    'gp120',
    'VIF',
    'APJ receptor',
    'Sgp',
    'Ribosome',
    'gpE',
    'Quorum Sensing',
    'Lysosomal membrane',
    'Mitochondrial membrane',
    'gpHA',
    'gD',
]

Sort by length descending so longer terms (like 'Virus Reverse Transcriptase') match first and then extract matching objects into a list for each row

In [ ]:
sorted_objects = sorted(known_objects, key=len, reverse=True)
pattern = '|'.join(re.escape(obj) for obj in sorted_objects)

In [ ]:
def parse_target_objects(val):
  if pd.isna(val):
    return []
  return re.findall(pattern, str(val))

Create the tokenised column

In [ ]:
# 3.
df['tokenised_TARGET OBJECT'] = df['TARGET OBJECT'].apply(parse_target_objects)

In [ ]:
# Check the result
print(df[['TARGET OBJECT', 'tokenised_TARGET OBJECT']].head(12))

                         TARGET OBJECT             tokenised_TARGET OBJECT
0                        Lipid Bilayer                     [Lipid Bilayer]
1                        Lipid Bilayer                     [Lipid Bilayer]
2                        Lipid Bilayer                     [Lipid Bilayer]
3                        Lipid Bilayer                     [Lipid Bilayer]
4                        Lipid Bilayer                     [Lipid Bilayer]
5                        Lipid Bilayer                     [Lipid Bilayer]
6                        Lipid Bilayer                     [Lipid Bilayer]
7                        Lipid Bilayer                     [Lipid Bilayer]
8                        Lipid Bilayer                     [Lipid Bilayer]
9                        Lipid Bilayer                     [Lipid Bilayer]
10                       Lipid Bilayer                     [Lipid Bilayer]
11  Lipid Bilayer    Virus replication  [Lipid Bilayer, Virus replication]

In [ ]:
df['tokenised_TARGET OBJECT'].describe()

count               25542
unique                 98
top       [Lipid Bilayer]
freq                19505
Name: tokenised_TARGET OBJECT, dtype: object

In [ ]:
df['tokenised_TARGET OBJECT'] = df['tokenised_TARGET OBJECT'].astype(str)

In [ ]:
df['tokenised_TARGET OBJECT'].head(15)

0                          ['Lipid Bilayer']
1                          ['Lipid Bilayer']
2                          ['Lipid Bilayer']
3                          ['Lipid Bilayer']
4                          ['Lipid Bilayer']
5                          ['Lipid Bilayer']
6                          ['Lipid Bilayer']
7                          ['Lipid Bilayer']
8                          ['Lipid Bilayer']
9                          ['Lipid Bilayer']
10                         ['Lipid Bilayer']
11    ['Lipid Bilayer', 'Virus replication']
12     ['Lipid Bilayer', 'Immunomodulation']
13                         ['Lipid Bilayer']
14                         ['Lipid Bilayer']
Name: tokenised_TARGET OBJECT, dtype: object

Work on the SYNTHESIS TYPE CATEGORY

In [ ]:
df['SYNTHESIS TYPE'].value_counts()

SYNTHESIS TYPE
Synthetic       21049
Ribosomal        3409
Nonribosomal     1084
Name: count, dtype: int64

Create the NAtural vs Synthetic Column

Non-Ribosomal and Ribosomal = Natural
Synthetic = SYnthetic

In [ ]:
import pandas as pd

origin_mapping = {
    'Ribosomal': 'Natural',
    'Nonribosomal': 'Natural',
    'Synthetic': 'Synthetic'
}

df['ORIGIN'] = df['SYNTHESIS TYPE'].map(origin_mapping)

print(df[['SYNTHESIS TYPE', 'ORIGIN']].head())

  SYNTHESIS TYPE     ORIGIN
0      Ribosomal    Natural
1      Ribosomal    Natural
2      Synthetic  Synthetic
3      Ribosomal    Natural
4      Ribosomal    Natural

Caluculation for seq length

In [ ]:
df['Length_of_Sequence'] = df['SEQUENCE'].str.len()

In [ ]:
df['Length_of_Sequence'].head()

0    51
1    37
2    38
3    81
4    86
Name: Length_of_Sequence, dtype: int64

Code for length distribution based class tagging

Reference source on peptide length classification:

Following paragraph is copied as it is from - "https://pmc.ncbi.nlm.nih.gov/articles/PMC9082820/"

Peptide length:
The size distribution of natural AMPs in the APD is shown in Figure 1B. The shortest peptide comprises two amino acids (aa) plus chemical modifications. The upper limit is defined by the peptides collected into the APD (currently less than 200 amino acids). Based on peptide length, they may be further grouped: ultrashort (2–9 aa), short (10–24 aa), medium (25–50 aa), and long (50–100 aa). The majority of AMPs (88%) are small with less than 50 amino acids (with a peak at 21–30 aa in Figure 1B). Approximately 10% contain 50–100 amino acids. AMPs with greater than 100 aa are antimicrobial proteins.

In [ ]:
import numpy as np

conditions = [
    (df['Length_of_Sequence'] >= 2) & (df['Length_of_Sequence'] <= 9),
    (df['Length_of_Sequence'] >= 10) & (df['Length_of_Sequence'] <= 24),
    (df['Length_of_Sequence'] >= 25) & (df['Length_of_Sequence'] <= 50),
    (df['Length_of_Sequence'] > 50) & (df['Length_of_Sequence'] <= 100),
    (df['Length_of_Sequence'] > 100)
]


choices = [
    'Ultrashort (2–9 aa)',
    'Short (10–24 aa)',
    'Medium (25–50 aa)',
    'Long (50–100 aa)',
    'Antimicrobial Protein (>100 aa)'
]


df['Length_Class'] = np.select(conditions, choices, default='Out of range (<2 aa)')

In [ ]:
# Quick check: View the distribution of your classifications
print(df['Length_Class'].value_counts())

Length_Class
Short (10–24 aa)                   15282
Ultrashort (2–9 aa)                 4987
Medium (25–50 aa)                   4583
Long (50–100 aa)                     504
Out of range (<2 aa)                 156
Antimicrobial Protein (>100 aa)       30
Name: count, dtype: int64

In [ ]:
df['Length_Class'].head()

0     Long (50–100 aa)
1    Medium (25–50 aa)
2    Medium (25–50 aa)
3     Long (50–100 aa)
4     Long (50–100 aa)
Name: Length_Class, dtype: object

In [ ]:
df1 = pd.read_csv("/content/peptides Animalia 0-2000.csv")
df2 = pd.read_csv("/content/peptides Animalia 2000-2645.csv")
df_kingdom_animalia = pd.concat([df1, df2], ignore_index=False)

In [ ]:
len(df_kingdom_animalia['NAME'].tolist())

#df_kingdom_animalia['NAME'].tolist()

2645

In [ ]:
df_kingdom_archaea = pd.read_csv("/content/peptides Archaea 0-10.csv")
df_kingdom_bacteria = pd.read_csv("/content/peptides bacteria 0-789.csv")
df_kingdom_fungi = pd.read_csv("/content/peptides fungi 0-307.csv")
df_kingdom_protista = pd.read_csv("/content/peptides protista 0-2.csv")
df_kingdom_virus = pd.read_csv("/content/peptides virus 0-2.csv")
df_kingdom_plantae = pd.read_csv("/content/peptides plantae 0-352.csv")

classifying based on kingdom

In [ ]:
_ANIMALIA = df_kingdom_animalia['NAME'].tolist()
_ARCHAEA = df_kingdom_archaea['NAME'].tolist()
_BACTERIA = df_kingdom_bacteria['NAME'].tolist()
_FUNGI = df_kingdom_fungi['NAME'].tolist()
_PROTISTA = df_kingdom_protista['NAME'].tolist()
_VIRUS = df_kingdom_virus['NAME'].tolist()
_PLANTAE = df_kingdom_plantae['NAME'].tolist()

In [ ]:
print(len(df_kingdom_animalia['NAME'].tolist()))
print(len(df_kingdom_archaea['NAME'].tolist()))
print(len(df_kingdom_bacteria['NAME'].tolist()))
print(len(df_kingdom_fungi['NAME'].tolist()))
print(len(df_kingdom_protista['NAME'].tolist()))
print(len(df_kingdom_virus['NAME'].tolist()))

2645
10
789
307
2
2

In [ ]:
df.columns.tolist()

['ID',
 'COMPLEXITY',
 'NAME',
 'N TERMINUS',
 'SEQUENCE',
 'C TERMINUS',
 'SYNTHESIS TYPE',
 'TARGET GROUP',
 'TARGET OBJECT',
 'tokenised_TARGET GROUP',
 'tokenised_TARGET OBJECT',
 'ORIGIN',
 'Length_of_Sequence',
 'Length_Class']

In [ ]:
import re

MULTI_SPLIT = re.compile(r"\s{2,}")

def split_multi(value):
    """Turn one raw multi-value DBAASP field into a list of tokens."""
    if value is None or str(value).strip() == "":
        return []
    return [p.strip() for p in MULTI_SPLIT.split(str(value).strip()) if p.strip()]

ACTIVITY_LABELS = {
    "Gram+":          "antibacterial_gram_pos",
    "Gram-":          "antibacterial_gram_neg",
    "Fungus":         "antifungal",
    "Virus":          "antiviral",
    "Cancer":         "anticancer",
    "Biofilm":        "antibiofilm",
    "Parasite":       "antiparasitic",
    "Insect":         "insecticidal",
    "Protista":       "antiprotozoal",
    "Mollicute":      "antimollicute",
    "Nematode":       "nematicidal",
    "Mammalian Cell": "mammalian_cytotoxic",
}

def add_activity_columns(df, raw_column="TARGET GROUP"):
    # step 1: tokenize the raw field
    tokens = df[raw_column].map(split_multi)

    # step 2: one boolean column per known activity
    for raw_token, clean_label in ACTIVITY_LABELS.items():
        df[clean_label] = tokens.map(lambda t, tok=raw_token: tok in t)

    # step 3 (optional extras): count + readable summary
    df["n_activities"] = tokens.map(len)
    df["activity_list"] = tokens.map(
        lambda t: "; ".join(ACTIVITY_LABELS.get(x, x) for x in t)
    )
    return df

In [ ]:
df

,ID,COMPLEXITY,NAME,N TERMINUS,SEQUENCE,C TERMINUS,SYNTHESIS TYPE,TARGET GROUP,TARGET OBJECT,tokenised_TARGET GROUP,tokenised_TARGET OBJECT,ORIGIN,Length_of_Sequence,Length_Class
0,1,Multimer,Distinctin,NaN,NLVSGLIEARKYLEQLHRKLKNCKV ENREVPPGFTALIKTLR...,NaN,Ribosomal,Gram+ Gram-,Lipid Bilayer,"['Gram+', 'Gram-']",['Lipid Bilayer'],Natural,51,Long (50–100 aa)
1,3,Multimer,Halocidin,NaN,WLNALLHHGLNCAKGVLA ALLHHGLNCAKGVLA,AMD AMD,Ribosomal,Gram+,Lipid Bilayer,['Gram+'],['Lipid Bilayer'],Natural,37,Medium (25–50 aa)
2,4,Multimer,Khal,NaN,KWLNALLHHGLNCAKGVLA ALLHHGLNCAKGVLA,AMD AMD,Synthetic,Gram+ Gram-,Lipid Bilayer,"['Gram+', 'Gram-']",['Lipid Bilayer'],Synthetic,38,Medium (25–50 aa)
3,6,Multi-Peptide,Enterocin X,NaN,SNDSLWYGVGQFMGKQANCITNHPVKHMIIPGYCLSKILG IA...,NaN,Ribosomal,Gram+,Lipid Bilayer,['Gram+'],['Lipid Bilayer'],Natural,81,Long (50–100 aa)
4,7,Multi-Peptide,EAFP1 + EAFP2,NaN,XTCASRCPRPCNAGLCCSIYGYCGSGNAYCGAGNCRCQCRG X...,NaN,Ribosomal,Fungus,Lipid Bilayer,['Fungus'],['Lipid Bilayer'],Natural,86,Long (50–100 aa)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25537,25808,Monomer,Dermatoxin-PD1 (1-18),NaN,SLGSFLKGVGKGLATVGK,AMD,Synthetic,Gram+ Gram- Fungus Mammalian Cell ...,Lipid Bilayer,"['Gram+', 'Gram-', 'Fungus', 'Mammalian Cell',...",['Lipid Bilayer'],Synthetic,18,Short (10–24 aa)
25538,25809,Monomer,Dermatoxin-PD1 (1-11),NaN,SLGSFLKGVGK,AMD,Synthetic,Gram+ Gram- Fungus Mammalian Cell ...,NaN,"['Gram+', 'Gram-', 'Fungus', 'Mammalian Cell',...",[],Synthetic,11,Short (10–24 aa)
25539,25810,Monomer,Cathelicidin MC-CATH1,NaN,GLKARAGRLPGLFGLLWDRIRNRGRRPRDVFENLSA,NaN,Ribosomal,Gram+ Gram- Cancer Fungus Mammalia...,Lipid Bilayer,"['Gram+', 'Gram-', 'Cancer', 'Fungus', 'Mammal...",['Lipid Bilayer'],Natural,36,Medium (25–50 aa)
25540,25811,Monomer,Cathelicidin MC-CATH2,NaN,GLKARVLRVNNVFRRLWDTLRNRGWRPRLFIRNLSPEEEP,NaN,Ribosomal,Gram+ Gram- Cancer Fungus Mammalia...,Lipid Bilayer,"['Gram+', 'Gram-', 'Cancer', 'Fungus', 'Mammal...",['Lipid Bilayer'],Natural,40,Medium (25–50 aa)
25541,25812,Monomer,Cathelicidin MC-CATH3,NaN,KLNAENLGERIKNAKKKVWEKIKSFGRRIKEFFRKPSPEGEP,NaN,Ribosomal,Gram+ Gram- Cancer Fungus Mammalia...,Lipid Bilayer,"['Gram+', 'Gram-', 'Cancer', 'Fungus', 'Mammal...",['Lipid Bilayer'],Natural,42,Medium (25–50 aa)

In [ ]:
print(df.duplicated().sum())

2000

## Tagging the combined database by kingdom

Each kingdom file (Animalia, Archaea, Bacteria, Fungi, Protista, Virus, Plantae) is a subset of the master `df` pulled from the same underlying DBAASP database, so every peptide keeps the same `ID` across every file it appears in — `ID` is the one column guaranteed to be unique and stable.

**Matching on `ID` instead of `NAME`**: the earlier `_ANIMALIA = df_kingdom_animalia['NAME'].tolist()` approach (cell above) matches on peptide name, but names in this dataset have inconsistent whitespace/formatting (e.g. `"Brevinin-2 related peptide B2RP   "`) and aren't guaranteed unique, so string matching on `NAME` will silently miss or mis-tag rows. `ID` doesn't have that problem, so we tag using `ID` instead.

In [ ]:
# One DataFrame per kingdom (reuses the variables already loaded above)
kingdom_frames = {
    'Animalia': df_kingdom_animalia,
    'Archaea':  df_kingdom_archaea,
    'Bacteria': df_kingdom_bacteria,
    'Fungi':    df_kingdom_fungi,
    'Protista': df_kingdom_protista,
    'Virus':    df_kingdom_virus,
    'Plantae':  df_kingdom_plantae,
}

In [ ]:
len(df_kingdom_animalia)

2645

In [ ]:
# Build ID -> [kingdoms] map. A list (not a single value) because a peptide
# could in principle show up in more than one kingdom file (e.g. dual-annotated
# in the source database) - we don't want to silently overwrite that.
id_to_kingdoms = {}
for kingdom, kdf in kingdom_frames.items():
    for pid in kdf['ID']:
        id_to_kingdoms.setdefault(pid, []).append(kingdom)

# Data-quality check: flag any ID claimed by more than one kingdom file
overlaps = {pid: ks for pid, ks in id_to_kingdoms.items() if len(ks) > 1}
print(f"{len(overlaps)} IDs appear in more than one kingdom file")
if overlaps:
    print(dict(list(overlaps.items())[:10]))  # peek at a few

22 IDs appear in more than one kingdom file
{23315: ['Animalia', 'Bacteria'], 6742: ['Archaea', 'Bacteria', 'Fungi'], 6743: ['Archaea', 'Bacteria', 'Fungi'], 18882: ['Archaea', 'Bacteria'], 18892: ['Archaea', 'Bacteria'], 18983: ['Archaea', 'Bacteria', 'Fungi'], 21680: ['Archaea', 'Bacteria'], 21683: ['Archaea', 'Bacteria'], 5372: ['Bacteria', 'Virus'], 5373: ['Bacteria', 'Virus']}

In [ ]:
# Tag the combined/master dataframe
df['KINGDOM'] = df['ID'].map(lambda pid: ', '.join(id_to_kingdoms.get(pid, [])))
df.loc[df['KINGDOM'] == '', 'KINGDOM'] = 'Unclassified'

print(df['KINGDOM'].value_counts())

KINGDOM
Unclassified                21158
Animalia                     2709
Bacteria                      897
Fungi                         374
Plantae                       371
Bacteria, Fungi                15
Archaea, Bacteria               6
Archaea, Bacteria, Fungi        4
Archaea                         3
Protista                        2
Bacteria, Virus                 2
Animalia, Bacteria              1
Name: count, dtype: int64

`Unclassified` rows are peptides present in the master `df` slice(s) you've loaded but not present in any of the kingdom file(s) you've loaded yet — as you add the remaining kingdom pagination files (e.g. the rest of Animalia beyond `0-2645`, or any kingdom you haven't pulled in), re-run the two cells above and the `Unclassified` count will keep shrinking. It should not be treated as "kingdom = none" until every kingdom file has been loaded.

In [ ]:
# Sanity check on a few tagged rows
df[df['KINGDOM'] != 'Unclassified'][['ID', 'NAME', 'KINGDOM']].head(10)

      ID                                  NAME   KINGDOM
8     11  Cathelicidin-1, CATH-1, Fowlicidin-1  Animalia
11    14    Brevinin-2 related peptide B2RP     Animalia
12    15                            Histatin 5  Animalia
13    16                    Distinctin chain 1  Animalia
32    36                    Distinctin chain 2  Animalia
33    37                                  PGLa  Animalia
38    54                   Halocidin subunit B  Animalia
39    55                   Halocidin subunit A  Animalia
41    57                             Tenecin-1  Animalia
127  160                           Tritrpticin  Animalia

In [ ]:
df.head()

,ID,COMPLEXITY,NAME,N TERMINUS,SEQUENCE,C TERMINUS,SYNTHESIS TYPE,TARGET GROUP,TARGET OBJECT,tokenised_TARGET GROUP,tokenised_TARGET OBJECT,ORIGIN,Length_of_Sequence,Length_Class,KINGDOM
0,1,Multimer,Distinctin,NaN,NLVSGLIEARKYLEQLHRKLKNCKV ENREVPPGFTALIKTLR...,NaN,Ribosomal,Gram+ Gram-,Lipid Bilayer,"['Gram+', 'Gram-']",['Lipid Bilayer'],Natural,51,Long (50–100 aa),Unclassified
1,3,Multimer,Halocidin,NaN,WLNALLHHGLNCAKGVLA ALLHHGLNCAKGVLA,AMD AMD,Ribosomal,Gram+,Lipid Bilayer,['Gram+'],['Lipid Bilayer'],Natural,37,Medium (25–50 aa),Unclassified
2,4,Multimer,Khal,NaN,KWLNALLHHGLNCAKGVLA ALLHHGLNCAKGVLA,AMD AMD,Synthetic,Gram+ Gram-,Lipid Bilayer,"['Gram+', 'Gram-']",['Lipid Bilayer'],Synthetic,38,Medium (25–50 aa),Unclassified
3,6,Multi-Peptide,Enterocin X,NaN,SNDSLWYGVGQFMGKQANCITNHPVKHMIIPGYCLSKILG IA...,NaN,Ribosomal,Gram+,Lipid Bilayer,['Gram+'],['Lipid Bilayer'],Natural,81,Long (50–100 aa),Unclassified
4,7,Multi-Peptide,EAFP1 + EAFP2,NaN,XTCASRCPRPCNAGLCCSIYGYCGSGNAYCGAGNCRCQCRG X...,NaN,Ribosomal,Fungus,Lipid Bilayer,['Fungus'],['Lipid Bilayer'],Natural,86,Long (50–100 aa),Unclassified

##Handling the unclassified data

In [ ]:
pd.crosstab(df['ORIGIN'], df['KINGDOM'] == 'Unclassified')

KINGDOM    False  True
ORIGIN
Natural     4372    121
Synthetic     12  21037

In [ ]:
import requests, concurrent.futures as cf, pandas as pd, os
from requests.adapters import HTTPAdapter

API_URL = "https://dbaasp.org/api/v1"
CHECKPOINT = "/content/kingdom_lookup.csv"
WORKERS = 60

session = requests.Session()
session.mount("https://", HTTPAdapter(pool_connections=WORKERS, pool_maxsize=WORKERS))
# ^ requests defaults pool_maxsize to 10 — without raising it, 60 threads bottleneck on 10 connections

def fetch(pid, timeout=8, retries=2):
    for _ in range(retries + 1):
        try:
            r = session.get(API_URL, params={"query": "peptide_card", "peptide_id": int(pid), "format": "json"}, timeout=timeout)
            if r.ok:
                d = r.json()
                src = d.get("source", {}) or {}
                return {"ID": pid, "KINGDOM_API": src.get("kingdom"), "SUBKINGDOM_API": src.get("subkingdom"),
                        "SOURCE_ORGANISM": src.get("source") or src.get("organism"),
                        "NCBI_ID": src.get("ncbi"), "STATUS": "ok"}
        except requests.RequestException:
            continue
    return {"ID": pid, "KINGDOM_API": None, "STATUS": "failed"}

done_ids, results = set(), []
if os.path.exists(CHECKPOINT):
    prev = pd.read_csv(CHECKPOINT)
    results, done_ids = prev.to_dict("records"), set(prev["ID"])

targets = [pid for pid in df.loc[df['KINGDOM'] == 'Unclassified', 'ID'].unique() if pid not in done_ids]

with cf.ThreadPoolExecutor(max_workers=WORKERS) as ex:
    futs = {ex.submit(fetch, pid): pid for pid in targets}
    for i, fut in enumerate(cf.as_completed(futs), 1):
        results.append(fut.result())
        if i % 1000 == 0:
            pd.DataFrame(results).to_csv(CHECKPOINT, index=False)
            print(f"{i}/{len(targets)}")

pd.DataFrame(results).to_csv(CHECKPOINT, index=False)

1000/19547
2000/19547
3000/19547
4000/19547
5000/19547
6000/19547
7000/19547
8000/19547
9000/19547
10000/19547
11000/19547
12000/19547
13000/19547
14000/19547
15000/19547
16000/19547
17000/19547
18000/19547
19000/19547

In [ ]:
domain_map = {
    'Bacteria': 'Bacteria',
    'Archaea': 'Archaea',
    'Animalia': 'Eukarya', 'Plantae': 'Eukarya', 'Fungi': 'Eukarya', 'Protista': 'Eukarya',
    'Virus': 'N/A (acellular; outside the three-domain system)',
}

In [ ]:
df[df.duplicated(subset='ID', keep=False)].sort_values('ID').head(20)

,ID,COMPLEXITY,NAME,N TERMINUS,SEQUENCE,C TERMINUS,SYNTHESIS TYPE,TARGET GROUP,TARGET OBJECT,tokenised_TARGET GROUP,tokenised_TARGET OBJECT,ORIGIN,Length_of_Sequence,Length_Class,KINGDOM
16000,18253,Monomer,HG2.67,FMOC,xXXXX,AMD,Synthetic,Gram+ Gram-,Lipid Bilayer,"['Gram+', 'Gram-']",['Lipid Bilayer'],Synthetic,5,Ultrashort (2–9 aa),Unclassified
18000,18253,Monomer,HG2.67,FMOC,xXXXX,AMD,Synthetic,Gram+ Gram-,Lipid Bilayer,"['Gram+', 'Gram-']",['Lipid Bilayer'],Synthetic,5,Ultrashort (2–9 aa),Unclassified
18001,18254,Monomer,HG2.41,FMOC,kKXXK,AMD,Synthetic,Gram+ Gram-,Lipid Bilayer,"['Gram+', 'Gram-']",['Lipid Bilayer'],Synthetic,5,Ultrashort (2–9 aa),Unclassified
16001,18254,Monomer,HG2.41,FMOC,kKXXK,AMD,Synthetic,Gram+ Gram-,Lipid Bilayer,"['Gram+', 'Gram-']",['Lipid Bilayer'],Synthetic,5,Ultrashort (2–9 aa),Unclassified
16002,18255,Monomer,HG2.73,FMOC,XXXXX,AMD,Synthetic,Gram+ Gram-,Lipid Bilayer,"['Gram+', 'Gram-']",['Lipid Bilayer'],Synthetic,5,Ultrashort (2–9 aa),Unclassified
18002,18255,Monomer,HG2.73,FMOC,XXXXX,AMD,Synthetic,Gram+ Gram-,Lipid Bilayer,"['Gram+', 'Gram-']",['Lipid Bilayer'],Synthetic,5,Ultrashort (2–9 aa),Unclassified
18003,18256,Monomer,HG2.89,DPhAc,xXXXX,AMD,Synthetic,Gram+ Gram-,Lipid Bilayer,"['Gram+', 'Gram-']",['Lipid Bilayer'],Synthetic,5,Ultrashort (2–9 aa),Unclassified
16003,18256,Monomer,HG2.89,DPhAc,xXXXX,AMD,Synthetic,Gram+ Gram-,Lipid Bilayer,"['Gram+', 'Gram-']",['Lipid Bilayer'],Synthetic,5,Ultrashort (2–9 aa),Unclassified
16004,18257,Monomer,HG2.75,DPhAc,xXX,AMD,Synthetic,Gram+ Gram- Mammalian Cell,Lipid Bilayer,"['Gram+', 'Gram-', 'Mammalian Cell']",['Lipid Bilayer'],Synthetic,3,Ultrashort (2–9 aa),Unclassified
18004,18257,Monomer,HG2.75,DPhAc,xXX,AMD,Synthetic,Gram+ Gram- Mammalian Cell,Lipid Bilayer,"['Gram+', 'Gram-', 'Mammalian Cell']",['Lipid Bilayer'],Synthetic,3,Ultrashort (2–9 aa),Unclassified
18005,18258,Monomer,HG2.77,DPhAc,XXX,AMD,Synthetic,Gram+ Gram-,Lipid Bilayer,"['Gram+', 'Gram-']",['Lipid Bilayer'],Synthetic,3,Ultrashort (2–9 aa),Unclassified
16005,18258,Monomer,HG2.77,DPhAc,XXX,AMD,Synthetic,Gram+ Gram-,Lipid Bilayer,"['Gram+', 'Gram-']",['Lipid Bilayer'],Synthetic,3,Ultrashort (2–9 aa),Unclassified
16006,18259,Monomer,HG2.81,FMOC,xXX,AMD,Synthetic,Gram+ Gram- Mammalian Cell,Lipid Bilayer,"['Gram+', 'Gram-', 'Mammalian Cell']",['Lipid Bilayer'],Synthetic,3,Ultrashort (2–9 aa),Unclassified
18006,18259,Monomer,HG2.81,FMOC,xXX,AMD,Synthetic,Gram+ Gram- Mammalian Cell,Lipid Bilayer,"['Gram+', 'Gram-', 'Mammalian Cell']",['Lipid Bilayer'],Synthetic,3,Ultrashort (2–9 aa),Unclassified
18007,18260,Monomer,HG2.83,DPhAc,xXX,AMD,Synthetic,Gram+ Gram-,Lipid Bilayer,"['Gram+', 'Gram-']",['Lipid Bilayer'],Synthetic,3,Ultrashort (2–9 aa),Unclassified
16007,18260,Monomer,HG2.83,DPhAc,xXX,AMD,Synthetic,Gram+ Gram-,Lipid Bilayer,"['Gram+', 'Gram-']",['Lipid Bilayer'],Synthetic,3,Ultrashort (2–9 aa),Unclassified
16008,18261,Monomer,KR-12 [V4W],NaN,KRIWQRIKDFLR,AMD,Synthetic,Gram+ Gram- Mammalian Cell,Lipid Bilayer,"['Gram+', 'Gram-', 'Mammalian Cell']",['Lipid Bilayer'],Synthetic,12,Short (10–24 aa),Unclassified
18008,18261,Monomer,KR-12 [V4W],NaN,KRIWQRIKDFLR,AMD,Synthetic,Gram+ Gram- Mammalian Cell,Lipid Bilayer,"['Gram+', 'Gram-', 'Mammalian Cell']",['Lipid Bilayer'],Synthetic,12,Short (10–24 aa),Unclassified
18009,18262,Monomer,KR-10 [V4W],C14,KRIWQRIKDF,AMD,Synthetic,Gram+ Gram- Mammalian Cell,Lipid Bilayer,"['Gram+', 'Gram-', 'Mammalian Cell']",['Lipid Bilayer'],Synthetic,10,Short (10–24 aa),Unclassified
16009,18262,Monomer,KR-10 [V4W],C14,KRIWQRIKDF,AMD,Synthetic,Gram+ Gram- Mammalian Cell,Lipid Bilayer,"['Gram+', 'Gram-', 'Mammalian Cell']",['Lipid Bilayer'],Synthetic,10,Short (10–24 aa),Unclassified

In [ ]:
df.head(1)

,ID,COMPLEXITY,NAME,N TERMINUS,SEQUENCE,C TERMINUS,SYNTHESIS TYPE,TARGET GROUP,TARGET OBJECT,tokenised_TARGET GROUP,tokenised_TARGET OBJECT,ORIGIN,Length_of_Sequence,Length_Class,KINGDOM
0,1,Multimer,Distinctin,NaN,NLVSGLIEARKYLEQLHRKLKNCKV ENREVPPGFTALIKTLR...,NaN,Ribosomal,Gram+ Gram-,Lipid Bilayer,"['Gram+', 'Gram-']",['Lipid Bilayer'],Natural,51,Long (50–100 aa),Unclassified

In [ ]:
df['DOMAIN'] = df['KINGDOM'].map(domain_map)

In [ ]:
df['DOMAIN'].value_counts()

DOMAIN
Eukarya     3456
Bacteria     897
Archaea        3
Name: count, dtype: int64

In [ ]:
df['KINGDOM'].value_counts()

KINGDOM
Unclassified                21158
Animalia                     2709
Bacteria                      897
Fungi                         374
Plantae                       371
Bacteria, Fungi                15
Archaea, Bacteria               6
Archaea, Bacteria, Fungi        4
Archaea                         3
Protista                        2
Bacteria, Virus                 2
Animalia, Bacteria              1
Name: count, dtype: int64

In [ ]:
import os, re, pandas as pd

OUTPUT_ROOT = "/content/subsets"
manifest = []

def slugify(value):
    value = re.sub(r'[\\/]+', '-', str(value).strip())   # "DNA / RNA" -> "DNA - RNA"
    value = re.sub(r'\s+', '_', value)
    return re.sub(r'[^\w\-]', '', value)

def write_subset(subset_df, dimension, label):
    folder = os.path.join(OUTPUT_ROOT, dimension)
    os.makedirs(folder, exist_ok=True)
    path = os.path.join(folder, f"{slugify(label)}.csv")
    subset_df.to_csv(path, index=False)
    manifest.append({"dimension": dimension, "value": label, "n_rows": len(subset_df), "file": path})

In [ ]:
for col, dim in [('DOMAIN', 'by_domain'), ('ORIGIN', 'by_origin'), ('Length_Class', 'by_length_class')]:
    for value, group in df.groupby(col):
        write_subset(group, dim, value)

In [ ]:
kingdoms = ['Animalia', 'Archaea', 'Bacteria', 'Fungi', 'Protista', 'Virus', 'Plantae']
for k in kingdoms:
    mask = df['KINGDOM'].str.contains(rf'\b{k}\b', na=False)
    write_subset(df[mask], 'by_kingdom', k)

write_subset(df[df['KINGDOM'].isin(['Unclassified', 'Not Applicable (Synthetic)'])], 'by_kingdom', 'Unresolved')

In [ ]:
ACTIVITY_LABELS

{'Gram+': 'antibacterial_gram_pos',
 'Gram-': 'antibacterial_gram_neg',
 'Fungus': 'antifungal',
 'Virus': 'antiviral',
 'Cancer': 'anticancer',
 'Biofilm': 'antibiofilm',
 'Parasite': 'antiparasitic',
 'Insect': 'insecticidal',
 'Protista': 'antiprotozoal',
 'Mollicute': 'antimollicute',
 'Nematode': 'nematicidal',
 'Mammalian Cell': 'mammalian_cytotoxic'}

In [ ]:
activity_cols = list(ACTIVITY_LABELS.values())   # antibacterial_gram_pos, antifungal, anticancer, antibiofilm, ...

In [ ]:
activity_cols

['antibacterial_gram_pos',
 'antibacterial_gram_neg',
 'antifungal',
 'antiviral',
 'anticancer',
 'antibiofilm',
 'antiparasitic',
 'insecticidal',
 'antiprotozoal',
 'antimollicute',
 'nematicidal',
 'mammalian_cytotoxic']

In [ ]:
df = add_activity_columns(df) # Call the function to add activity columns to the DataFrame
for col in activity_cols:
    write_subset(df[df[col] == True], 'by_target_group', col)

In [ ]:
tokenised_objects = df['TARGET OBJECT'].apply(parse_target_objects)   # your existing function, applied fresh
for obj in known_objects:
    mask = tokenised_objects.apply(lambda lst: obj in lst)
    write_subset(df[mask], 'by_target_object', obj)

In [ ]:
pd.DataFrame(manifest).to_csv(os.path.join(OUTPUT_ROOT, "manifest.csv"), index=False)

import shutil
shutil.make_archive("/content/subsets_export", 'zip', OUTPUT_ROOT)   # one downloadable deliverable

'/content/subsets_export.zip'

In [ ]:
combo = df[(df['ORIGIN'] == 'Natural') & df['KINGDOM'].str.contains('Bacteria', na=False) & (df['antifungal']) & (df['Length_Class'] == 'Short (10–24 aa)')]

In [ ]:
df = df.drop_duplicates(subset='ID', keep='first').reset_index(drop=True)
print(df.shape)

(23542, 30)

In [ ]:
combo

,ID,COMPLEXITY,NAME,N TERMINUS,SEQUENCE,C TERMINUS,SYNTHESIS TYPE,TARGET GROUP,TARGET OBJECT,tokenised_TARGET GROUP,...,anticancer,antibiofilm,antiparasitic,insecticidal,antiprotozoal,antimollicute,nematicidal,mammalian_cytotoxic,n_activities,activity_list
1578,1688,Monomer,"Gramicidin S, GS",NaN,VXLfPVXLfP,NaN,Nonribosomal,Gram+ Gram- Parasite Cancer Fungus...,Lipid Bilayer,"['Gram+', 'Gram-', 'Parasite', 'Cancer', 'Fung...",...,True,True,True,False,False,False,False,True,7,antibacterial_gram_pos; antibacterial_gram_neg...
1974,2121,Monomer,Microcin J25,NaN,GGAGHVPEYFVGIGTPISFYG,NaN,Ribosomal,Gram+ Gram- Cancer Fungus Mammalia...,Cytoplasmic Protein Lipid Bilayer,"['Gram+', 'Gram-', 'Cancer', 'Fungus', 'Mammal...",...,True,False,False,False,False,False,False,True,5,antibacterial_gram_pos; antibacterial_gram_neg...
3042,3245,Monomer,Antimicrobial protein BL-A60,Ch,LYKLVKVVLNM,TA,Ribosomal,Gram+ Gram- Fungus,Lipid Bilayer,"['Gram+', 'Gram-', 'Fungus']",...,False,False,False,False,False,False,False,False,3,antibacterial_gram_pos; antibacterial_gram_neg...
3113,3316,Monomer,"Tyrocidine A, TA",NaN,fPFfNQYVXL,NaN,Nonribosomal,Gram+ Gram- Parasite Cancer Fungus...,Membrane Protein Lipid Bilayer DNA / RNA,"['Gram+', 'Gram-', 'Parasite', 'Cancer', 'Fung...",...,True,True,True,False,False,False,False,True,7,antibacterial_gram_pos; antibacterial_gram_neg...
3722,3927,Monomer,Antimicrobial peptide EP-20,NaN,EGPVGLADPDGPASAPLGAP,NaN,Ribosomal,Fungus,Lipid Bilayer,['Fungus'],...,False,False,False,False,False,False,False,False,1,antifungal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23059,23323,Monomer,Trichormamide C,NaN,xVxAxQXnTPlT,NaN,Nonribosomal,Gram+ Gram- Cancer Fungus,Lipid Bilayer,"['Gram+', 'Gram-', 'Cancer', 'Fungus']",...,True,False,False,False,False,False,False,False,4,antibacterial_gram_pos; antibacterial_gram_neg...
23060,23324,Monomer,Trichormamide D,NaN,xQXPSylVfLG,NaN,Nonribosomal,Gram+ Gram- Cancer Fungus,Lipid Bilayer,"['Gram+', 'Gram-', 'Cancer', 'Fungus']",...,True,False,False,False,False,False,False,False,4,antibacterial_gram_pos; antibacterial_gram_neg...
23440,23704,Monomer,Lariocidin,NaN,SKKSKPGDGKFGRGVKRG,NaN,Ribosomal,Gram+ Gram- Fungus Mammalian Cell,DNA / RNA,"['Gram+', 'Gram-', 'Fungus', 'Mammalian Cell']",...,False,False,False,False,False,False,False,True,4,antibacterial_gram_pos; antibacterial_gram_neg...
24950,25221,Monomer,Cinnamosyn,2-Me-CIN,XFlVAxGPXL,NaN,Nonribosomal,Gram+ Gram- Cancer Fungus Mammalia...,Unknown,"['Gram+', 'Gram-', 'Cancer', 'Fungus', 'Mammal...",...,True,False,False,False,False,False,False,True,5,antibacterial_gram_pos; antibacterial_gram_neg...
24983,25254,Monomer,Cinnapeptin,2-Me-CIN,xfLykXSYxX,NaN,Nonribosomal,Gram+ Gram- Fungus,Unknown,"['Gram+', 'Gram-', 'Fungus']",...,False,False,False,False,False,False,False,False,3,antibacterial_gram_pos; antibacterial_gram_neg...

In [ ]:
df['KINGDOM'].value_counts()

KINGDOM
Unclassified                19547
Animalia                     2586
Bacteria                      742
Plantae                       349
Fungi                         291
Bacteria, Fungi                12
Archaea, Bacteria               4
Archaea, Bacteria, Fungi        3
Archaea                         3
Protista                        2
Bacteria, Virus                 2
Animalia, Bacteria              1
Name: count, dtype: int64